# Generated by Django 4.2.6 on 2023-10-30 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("link_imagem", models.URLField()),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Conexao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conexaoA",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conexoes_a",
                        to="grafos.ator",
                    ),
                ),
                (
                    "conexaoB",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conexoes_b",
                        to="grafos.ator",
                    ),
                ),
            ],
        ),
    ]
